text = "GTTAGTAACTATGTAACTATGAACTATGTCCAACTATGTTAAACTATGAAACTATGCCCCTTCCGACAAACTATGAAATTGAACTATGAGGAAACTATGCAAACTATGAAACTATGACTTAGAAACTATGGAACTATGAACTATGCGGACAAACTATGAACTATGTTGGGACCAACTATGAAACTATGCTACGATTAATAACTATGGAACAACTATGAAACTATGAAACTATGAACTATGTAACTATGAATTAACAAACTATGAACTATGAACTATGAACTATGACGTAACTATGCTGATTCAACTATGACGCTCTCAAAGAACTATGGTCGAACTATGAACTATGCGCTGTGGTTAACTATGAACTATGAGAACTATGGGTCAACTATGCAACTATGTGAACTATGCTAACTATGAACTATGTATAACTATGTAACTATGAGTCAACTATGTCGAAACTATGAACTATGTAACTATGTACGAGTTTGAACTATGCCGCAACTATGAACTATGATAAAACTATGAAACTATGTACCAACTATGCAAACAAACTATGATTAAACTATGATAAACTATGCAACTATGGAACTATGAAATAAGCAGAACTATGAACTATGCAAACTATGGCGTTCATCAACTATGAACATAAACTATGCCAGAAGCCAGTGGCAACTATGAACTATGTAAACTATGAATAACTATGATACTTGCCGGCACAACTATGAGTAAACTATGAAAACTATGAACTATGAAACTATGAACTATGAGGAACTATGAACTATGTCAACTATGAACTATGAACTATGGAAACTATGATCAACTATGAACTATGCCGGCCAACTATGGACATTACCCGGAGACAACTATGCAACTATGAACTATGGTACAACTATGGATAACTATGCGAAACTATGAACTATGAAGTAACTATGAACTATGAACTATGAACTATGCTTAACTATG"
pattern = "AACTATGAA"

def pattern_count(text, pattern):
    text_length = len(text)
    pattern_length = len(pattern)

    count = 0
    for i in range(text_length - pattern_length + 1):
        substring = text[i:i+pattern_length]
        if substring == pattern:
            count = count + 1
        
    return count

count = pattern_count(text, pattern)
print(count)